# Distroless images:
# defaultBaseImage: gcr.io/distroless/static:nonroot
#
# https://pkg.go.dev/cmd/link
# -s: omit symbol/debug info
# -w: omit DWARF symbol table
# -X importpath.name=value: sets name to value
defaultBaseImage: gcr.io/k8s-prow/git:v20220215-ddc3ad9
builds:
  - id: pga
    dir: prow/cmd/pga
    main: .
    ldflags:
      - -s -w
      - -X cncf.io/cncf-infra/pga/version.Version={{.Env.VERSION}}
      - -X cncf.io/cncf-infra/pga/version.Name=hook
