# Distroless images:
# defaultBaseImage: gcr.io/distroless/static:nonroot
#
# https://pkg.go.dev/cmd/link
# -s: omit symbol/debug info
# -w: omit DWARF symbol table
# -X importpath.name=value: sets name to value
defaultBaseImage: alpine:3.15
builds:
  - id: pga
    dir: .
    main: prow/cmd/pga
    ldflags:
      - -s -w
      - -X cncf.io/cncf-infra/pga/version.Version={{.Env.VERSION}}
      - -X cncf.io/cncf-infra/pga/version.Name=pga
