# Plugin configuration
# Inspired by https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml
---
triggers:
  - repos:
      - cncf-infra/mock-project-repo
    join_org_url: "https://git.k8s.io/community/community-membership.md#member"
    only_org_members: true
    trigger_github_workflows: true

owners:
  skip_collaborators:
    - cncf-infra/mock-project-repo

approve:
  - repos:
      - cncf-infra/mock-project-repo
    require_self_approval: false
    lgtm_acts_as_approve: true

help:
  help_guidelines_summary: |
    Please ensure that the issue body includes answers to the following questions:
    - Why are we solving this issue?
    - To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?
    - Does this issue have zero to low barrier of entry?
    - How can the assignee reach out to you for help?

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s: 10
  m: 30
  l: 100
  xl: 500
  xxl: 1000

label:
  additional_labels:
    # This label is used by the API review process
    # https://git.k8s.io/community/sig-architecture/api-review-process.md#mechanics
    - api-review
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash
    # This label, for k/website, identifies issues relevant to https://katacoda.com/
    - team/katacoda
    # This label, for k/website, identifies PRs with large refactoring changes
    - refactor

lgtm:
  - repos:
      - cncf-infra/mock-project-repo
    review_acts_as_lgtm: true
  - repos:
      - kubernetes/website
    store_tree_hash: true

blunderbuss:
  max_request_count: 2
  use_status_availability: false
  exclude_approvers: false

cat:
  key_path: /etc/cat-api/api-key

goose:
  key_path: /etc/unsplash-api/honk.txt

heart:
  adorees:
    - mirandachrist
  commentregexp: ".*"


welcome:
  - repos:
      - cncf-infra/mock-project-repo
    message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. <br><br>If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Kubernetes. :smiley:"

require_matching_label:
  - missing_label: do-not-merge/needs-kind
    org: cncf-infra
    repo: mock-project-repo
    prs: true
    regexp: ^kind/
  - missing_label: do-not-merge/needs-sig
    org: cncf-infra
    repo: mock-project-repo
    prs: true
    regexp: ^(sig|wg|committee)/
    # Define needs-sig separately for issues so that we only comment on issues.
  - missing_label: needs-sig
    org: cncf-infra
    repo: mock-project-repo
    issues: true
    regexp: ^(sig|wg|committee)/
    missing_comment: |
      There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
      - `/sig <group-name>`
      - `/wg <group-name>`
      - `/committee <group-name>`

      Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
  # Needs triage configuration
  - missing_label: needs-triage
    org: cncf-infra
    repo: mock-project-repo
    issues: true
    prs: true
    regexp: ^triage/accepted$
    missing_comment: |
      This issue is currently awaiting triage.

      If a SIG or subproject determines this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.

      The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.
  - missing_label: needs-triage
    org: cncf-infra
    repo: mock-project-repo
    issues: true
    regexp: ^triage/accepted$
    missing_comment: |
      This issue is currently awaiting triage.

      CNCF-infra takes a lead on issue triage for this website, but any Kubernetes member can accept issues by applying the `triage/accepted` label.

      The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.
  - missing_label: needs-priority
    org: cncf-infra
    repo: mock-project-repo
    prs: true
    regexp: ^priority/

retitle:
  allow_closed_issues: true

cherry_pick_unapproved:
  comment: |
    This cherry pick PR is for a release branch and has not yet been approved by [Release Managers](https://k8s.io/releases/release-managers).
    Adding the `do-not-merge/cherry-pick-not-approved` label.

    To merge this cherry pick, it must first be approved (`/lgtm` + `/approve`) by the relevant OWNERS.

    **AFTER** it has been approved by code owners, please leave the following comment on a line **by itself, with no leading whitespace**: **/cc kubernetes/release-managers**

    (This command will request a cherry pick review from [Release Managers](https://github.com/orgs/kubernetes/teams/release-managers) and should work for all GitHub users, whether they are members of the Kubernetes GitHub organization or not.)

    For details on the patch release process and schedule, see the [Patch Releases](https://k8s.io/releases/patch-releases) page.

# Enabled plugins per repo.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
plugins:
  cncf-infra/mock-project-repo:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - cla
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - owners-label
      - pony
      - retitle
      - shrug
      - sigmention
      - size
      - skip
      - transfer-issue
      - trick-or-treat
      - verify-owners
      - welcome
      - wip
      - yuks

