# Plugin configuration
# Inspired by https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml
---
triggers:
  - repos:
      - kubernetes-sigs/cloud-provider-azure
    join_org_url: "https://git.k8s.io/community/community-membership.md#member"
    only_org_members: true
    trigger_github_workflows: true
  - repos:
      - kubernetes
      - kubernetes-client
      - kubernetes-csi
      - kubernetes-sigs
    join_org_url: "https://git.k8s.io/community/community-membership.md#member"
    only_org_members: true
  - repos:
      - google/cadvisor
      - GoogleCloudPlatform/k8s-multicluster-ingress
    join_org_url: "https://git.k8s.io/community/community-membership.md#member"
  - repos:
      - containerd/cri
    join_org_url: "https://github.com/containerd/project/blob/main/MAINTAINERS"
  - repos:
      - containerd/containerd
    join_org_url: "https://github.com/containerd/project/blob/main/MAINTAINERS"
  - repos:
      - bazelbuild
  - repos:
      - cncf-infra/mock-project-repo

owners:
  mdyamlrepos:
    - kubernetes/website
  skip_collaborators:
    - kubernetes-sigs/contributor-playground

approve:
  - repos:
      - cncf-infra/mock-project-repo
    require_self_approval: false
    lgtm_acts_as_approve: true
    ignore_review_state: false

help:
  help_guidelines_summary: |
    Please ensure that the issue body includes answers to the following questions:
    - Why are we solving this issue?
    - To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?
    - Does this issue have zero to low barrier of entry?
    - How can the assignee reach out to you for help?

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s: 10
  m: 30
  l: 100
  xl: 500
  xxl: 1000

label:
  additional_labels:
    # This label is used by the API review process
    # https://git.k8s.io/community/sig-architecture/api-review-process.md#mechanics
    - api-review
    # These labels are used to make Tide merge with a non-default merge method
    - tide/merge-method-merge
    - tide/merge-method-rebase
    - tide/merge-method-squash
    # This label, for k/website, identifies issues relevant to https://katacoda.com/
    - team/katacoda
    # This label, for k/website, identifies PRs with large refactoring changes
    - refactor

  restricted_labels:
    kubernetes/kubernetes:
      # Security Response Committee (SRC) is allowed to add this label,
      # to new and existing GitHub Issues and PRs that announce a fixed CVE triaged by SRC
      - allowed_teams:
          - security-response-committee
        # SIG Security Tooling Lead is an allowed user to assist SRC in this CVE feed automation
        allowed_users:
          - pushkarj
        # This label is used to filter/tag CVEs announced by SRC
        label: official-cve-feed

lgtm:
  - repos:
      - cncf-infra/mock-project-repo

blunderbuss:
  max_request_count: 2
  use_status_availability: true

cat:
  key_path: /etc/cat-api/api-key

goose:
  key_path: /etc/unsplash-api/honk.txt

# Enabled plugins per repo.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
plugins:
  # Enable the following for any bazelbuild repo (rules_k8s, rules_docker) that sends prow webhooks
  # Repos that do not send prow webhooks will see no effect.

  cncf-infra/mock-project-repo:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - cla
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - milestoneapplier
      - owners-label
      - pony
      - retitle
      - shrug
      - sigmention
      - size
      - skip
      - slackevents
      - testfreeze
      - transfer-issue
      - trick-or-treat
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks
