name: Publish

on:
  push:
    branches: ["27150"]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.4
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.5
      - run: VERSION=main ko publish --bare ./prow/cmd/pga
